import { Geist, Geist_Mono, Bevan, Bree_Serif } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const bevan = Bevan({
  variable: "--font-bevan",
  subsets: ["latin"],
  weight: ["400"],
  style: ["normal", "italic"],
});

const breeSerif = Bree_Serif({
  variable: "--font-Bree-Serif",
  subsets: ["latin"],
  weight: ["400"],
  style: ["normal"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


// className={`${bevan.variable} antialiased`}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={breeSerif.className}
      >
        {children}
      </body>
    </html>
  );
}
